# SPDX-FileCopyrightText: 2025 Digg - The Agency for Digital Government
#
# SPDX-License-Identifier: CC0-1.0

version = 1

# Main project files
[[annotations]]
path = [
    "CHANGELOG.md",
    "README.md",
    "docs/DEVELOPMENT.md",
    "REUSE.toml",
    "pom.xml",
    "**/*.cddl",
    "renovate.json",
    "jreleaser.yml",
    ".mvn/settings.xml",
    "**/*/pmd_default_java.xml",
    "**/*/resources/**/*.json",
    "**/*/resources/**/*.html",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "2025 diggsweden/eudiw-wallet-issuer-poc"
SPDX-License-Identifier = "CC0-1.0"


[[annotations]]
path = [
    "**/*/eclipse-java-google-style.xml",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "google/styleguide"
SPDX-License-Identifier = "CC-BY-3.0"


[[annotations]]
path = [
    "**/*/google_checks.xml",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "checkstyle/checkstyle"
SPDX-License-Identifier = "CC0-1.0"