server:
  use-forward-headers: true
  forward-headers-strategy: NATIVE
  #ssl:
  #  certificate: ${HOME}/.config/devcerts/wallet-cert.pem
  #  certificate-private-key: ${HOME}/.config/devcerts/wallet-key.pem
  servlet:
    session:
      cookie:
        same-site: "none"
        http-only: true
        secure: false

logging:
  level:
    org.springframework.security: trace
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: [ "prometheus", "health", "info", "metrics" ]

eudiw:
  issuer: https://local.dev.swedenconnect.se:9090
  issuerBaseUrl: https://local.dev.swedenconnect.se:9090
  authHost: https://local.dev.swedenconnect.se:9090
  credentialHost: https://local.dev.swedenconnect.se:9090
  expHours: 24
  clientId: eudiw-client
  credentialOfferTtlInSeconds: 600
  signedMetaData: true
  trust-store:
    location: classpath:certificates/verifier.p12
    password: "verifier"
    alias: "verifier"

  redirectUris:
    - "https://local.dev.swedenconnect.se:9091/callback-test-1-authorisation-flow"
    - "https://local.dev.swedenconnect.se:9091"

  swedenconnect:
    base-url: https://local.dev.swedenconnect.se:9060/id-backend/auth
    client: wallet-dev
    return-base-url: https://local.dev.swedenconnect.se:9090/auth/return

  token-issuer-cert:
    - cert-location: classpath:dev/tokenSigner.crt
      kid: tokenSigner-1

