server:
  port: 9090
  ssl:
    enabled: true
    key-store-type: JKS
    key-store: classpath:keystores/local.dev.swedenconnect.se.jks
    key-store-password: changeit
    key-alias: local.dev.swedenconnect.se

logging:
  level:
    org:
      springframework:
        web:
          filter:
            CommonsRequestLoggingFilter: DEBUG
        security: debug
  error:
    whitelabel:
      enabled: false
spring:
  main:
    allow-bean-definition-overriding: true
  data:
    redis:
      host: "local.dev.swedenconnect.se"
      port: 6379
      database: 0
      username: "default"
      password: "secret"
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
      additional-paths: src/main/resources/templates/
      poll-interval: 1s
      quiet-period: 400ms
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
  resources:
    static-locations: file:src/main/resources/static/
    cache:
      period: 0
  ssl:
    bundle:
      pem:
        rest:
          truststore:
            # certificate path works in local sc-environment if the repos are located side by side
            # otherwise: set the filepath with SPRING_SSL_BUNDLE_PEM_REST_TRUSTSTORE_CERTIFICATE environment variable
            certificate: classpath:keystores/local.dev.swedenconnect.se-cert.pem

eudiw:
  issuer: https://local.dev.swedenconnect.se:9090
  issuerBaseUrl: https://local.dev.swedenconnect.se:9090
  authHost: https://local.dev.swedenconnect.se:9090
  credentialHost: https://local.dev.swedenconnect.se:9090
  issuerConfig:
    host: local.dev.swedenconnect.se
    port: 9090
    scheme: https
    contextPath: ""
  reference-idp:
    host: local.dev.swedenconnect.se
    port: 9020
    scheme: https
    context-path: "/idp"
  id-proxy-frontend:
    host: local.dev.swedenconnect.se
    port: 9065
    scheme: https
    context-path: "/id-frontend"
  expHours: 24
  clientId: 1234567891
  credentialOfferTtlInSeconds: 600
  trust-store:
    location: file:src/test/resources/certificates/truststore.p12
    password: secret
    alias: rootca
  #eudiw-client

  openidFederation:
    baseUrl:  https://local.dev.swedenconnect.se:9040/oidfed
    trustMarkId: https://local.dev.swedenconnect.se/trust-mark-id/pid-issuer
    walletProviderAnchor: https://local.dev.swedenconnect.se:9040/oidfed/wallet-provider
    walletBaseUri: https://local.dev.swedenconnect.se/wallets/
    subject: https://local.dev.swedenconnect.se:9090
    trustListTtlInSeconds: 60
    authorityHints:
      - "https://local.dev.swedenconnect.se:9040/oidfed/intermediate"

  valkey:
    host: local.dev.swedenconnect.se
    port: 6379
  issuerSignerKeyPemFile: "file:../eudiw-prototype/sc-environment/config/openid-fed/keystores/issuer-jwt-ec256-key-pair.pem"
  redirectUris:
    - "https://local.dev.swedenconnect.se:9091/callback-test-1-authorisation-flow"
    - "https://local.dev.swedenconnect.se:9091/callback-test-2-pre-authorisation-flow"
    - "https://local.dev.swedenconnect.se:9091/callback-test-3-par"
    - "https://local.dev.swedenconnect.se:9091"
    - "https://local.dev.swedenconnect.se:9443/callback-test-1-authorisation-flow"
    - "https://local.dev.swedenconnect.se:9443/callback-test-2-pre-authorisation-flow"
    - "https://local.dev.swedenconnect.se:9443/callback-test-3-par"
    - "https://local.dev.swedenconnect.se:9443/callback-test-4-authorisation-flow-authorization-details"
    - "https://local.dev.swedenconnect.se:9443"
    - "eu.europa.ec.euidi://authorization"
    - "http://localhost:8080"
  swedenconnect:
    base-url: https://local.dev.swedenconnect.se:9060/id-backend/auth
    client: wallet-dev
    return-base-url: https://local.dev.swedenconnect.se:9090/auth/return

  token-issuer-cert:
    - cert-location: classpath:dev/tokenSigner.crt
      kid: tokenSigner-1
    - cert-location: file:../eudiw-prototype/sc-environment/config/openid-fed/keystores/wp-certificate.crt
      kid: wp-1
  ewc-itb:
    idp: "http://local.dev.swedenconnect.se/idp"

credential:
  bundles:
    pem:
      issuercredential:
        #public-key: file:../eudiw-prototype/sc-environment/config/openid-fed/keystores/issuer-jwt-ec256-public-key.pem
        private-key: file:../eudiw-prototype/sc-environment/config/openid-fed/keystores/issuer_private_pkcs8.key
        #./pkcs8/private_pkcs8.key
        certificates: file:../eudiw-prototype/sc-environment/config/openid-fed/keystores/issuer-certificate.crt
        #./pkcs8/certificate.crt

        #name: "Issuer credential"
  bundle:
    monitoring:
      health-endpoint-enabled: true
