# SPDX-FileCopyrightText: 2024 Digg - The Agency for Digital Government
#
# SPDX-License-Identifier: CC0-1.0

---
name: MegaLinter
on:
  workflow_call: # yamllint disable-line rule:truthy

permissions:
  contents: read

env:
  MEGALINTER_CONFIG: ./development/megalinter.yml

jobs:
  megalinter:
    name: Megalinter analysis
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    steps:
      - name: Harden GitHub runner
        uses: step-security/harden-runner@cb605e52c26070c328afc4562f0b4ada7618a84e # v2.10.4
        with:
          egress-policy: audit

      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 10

      - name: MegaLinter lint
        id: ml
        uses: oxsecurity/megalinter@1fc052d03c7a43c78fe0fee19c9d648b749e0c01 # v8.3.0
        env:
          DEFAULT_WORKSPACE: .

      - name: Upload MegaLinter scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@ee117c905ab18f32fa0f66c2fe40ecc8013f3e04 # v3.28.4
        with:
          sarif_file: megalinter-reports/megalinter-report.sarif
